platform :ios, '8.0'
use_frameworks!

target 'Cardqu' do
   pod 'Alamofire', '~> 4.5.0'
   pod 'HandyJSON', '~> 4.0.0-beta.1'
   pod 'SnapKit', '~> 4.0.0'
   pod 'ReactiveCocoa', '~> 7.0'
   pod 'WechatOpenSDK'
end
